# Generated by Django 4.2.10 on 2024-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_slug_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
