# Generated by Django 4.2.10 on 2024-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('pk', 'بسته')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
