# Generated by Django 4.2.10 on 2024-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('pk', 'بسته'), ('st', 'یک دست')], max_length=10),
        ),
    ]
