# Generated by Django 4.2.10 on 2024-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('کیلوگرم', 'kg'), ('بسته', 'pk'), ('یک دست', 'st')], max_length=10),
        ),
    ]
