# Generated by Django 4.2.10 on 2024-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='shamsi',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
