# Generated by Django 4.2.10 on 2024-02-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=150)),
                ('product_price', models.PositiveIntegerField()),
                ('product_quantity', models.PositiveSmallIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order.order')),
            ],
            options={
                'verbose_name': 'orderproduct',
                'verbose_name_plural': 'orderproducts',
                'ordering': ('created',),
            },
        ),
    ]
