# Generated by Django 4.2.10 on 2024-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_address_order_finally_price_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shamsi',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shamsi',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
