# Generated by Django 4.2.10 on 2024-02-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_shamsi_orderitem_shamsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver',
            field=models.BooleanField(default=False),
        ),
    ]
